name : hello-fittrack
on: [workflow_dispatch]
jobs:
  build: 
      runs-on: ubuntu-latest
      steps:
        - name : echo
          run : echo ${{github.actor}}
  test: 
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name : echo
          run : echo ${{github.actor}}
  
